use crate::error::BuilderError;
use crate::identifiers::*;
use crate::value::*;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Distributed tracing context attached to a message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraceContext {
    /// Globally unique trace identifier.
    pub trace_id: String,
    /// Identifier for the current span within the trace.
    pub span_id: String,
    /// Identifier for the parent span, if any.
    pub parent_span_id: Option<String>,
}

/// Universal envelope for all inter-module communication.
///
/// Every message exchanged between modules is wrapped in this envelope.
/// It carries routing metadata (source, destination), tracing context,
/// delivery guarantees (priority, TTL), and the opaque payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageEnvelope {
    // MANDATORY
    /// Globally unique message identifier.
    pub id: MessageId,
    /// Correlation ID grouping related messages.
    pub correlation_id: CorrelationId,
    /// ID of the message that caused this one, if any.
    pub causation_id: Option<CausationId>,
    /// Module that sent this message.
    pub source: ModuleId,
    /// Target module, if directed (None for broadcast).
    pub destination: Option<ModuleId>,
    /// Timestamp of message creation.
    pub timestamp: DateTime<Utc>,
    /// Opaque binary payload.
    pub payload: Vec<u8>,
    /// Content type describing the payload encoding.
    pub content_type: ContentType,

    // CONDITIONAL
    /// Delivery priority.
    pub priority: Priority,
    /// Time-to-live relative to `timestamp`; expired messages may be dropped.
    pub ttl: Option<chrono::Duration>,

    // RUNTIME (set by Event Bus)
    /// Monotonically increasing sequence number assigned by the bus.
    pub sequence: u64,
    /// Number of delivery retries attempted so far.
    pub retry_count: u32,

    // TRACE
    /// Distributed tracing context, if any.
    pub trace_context: Option<TraceContext>,
}

impl MessageEnvelope {
    /// Create a new `MessageEnvelopeBuilder`.
    pub fn builder() -> MessageEnvelopeBuilder {
        MessageEnvelopeBuilder::default()
    }

    /// Returns `true` if this message has expired based on `timestamp` + `ttl`.
    ///
    /// When `ttl` is `None` the message never expires.
    pub fn is_expired(&self) -> bool {
        self.ttl
            .is_some_and(|ttl| Utc::now() > self.timestamp + ttl)
    }
}

/// Builder pattern for constructing `MessageEnvelope`.
///
/// Only `source`, `content_type`, and `payload` are required;
/// other fields get sensible defaults.
#[derive(Debug, Clone)]
pub struct MessageEnvelopeBuilder {
    correlation_id: CorrelationId,
    causation_id: Option<CausationId>,
    source: Option<ModuleId>,
    destination: Option<ModuleId>,
    timestamp: Option<DateTime<Utc>>,
    payload: Option<Vec<u8>>,
    content_type: Option<ContentType>,
    priority: Priority,
    ttl: Option<chrono::Duration>,
    trace_context: Option<TraceContext>,
}

/// Provide a default builder with random correlation_id and normal priority.
impl Default for MessageEnvelopeBuilder {
    fn default() -> Self {
        Self {
            correlation_id: CorrelationId::new(),
            causation_id: None,
            source: None,
            destination: None,
            timestamp: None,
            payload: None,
            content_type: None,
            priority: Priority::default(),
            ttl: None,
            trace_context: None,
        }
    }
}

impl MessageEnvelopeBuilder {
    /// Create a new builder with the three required fields pre-set.
    pub fn new(source: ModuleId, content_type: ContentType, payload: Vec<u8>) -> Self {
        Self::default()
            .source(source)
            .content_type(content_type)
            .payload(payload)
    }

    /// Set the source module.
    pub fn source(mut self, source: ModuleId) -> Self {
        self.source = Some(source);
        self
    }

    /// Set the content type.
    pub fn content_type(mut self, content_type: ContentType) -> Self {
        self.content_type = Some(content_type);
        self
    }

    /// Set the payload.
    pub fn payload(mut self, payload: Vec<u8>) -> Self {
        self.payload = Some(payload);
        self
    }

    /// Set the correlation ID. A random one is generated by default.
    pub fn correlation_id(mut self, id: CorrelationId) -> Self {
        self.correlation_id = id;
        self
    }

    /// Set the causation ID.
    pub fn causation_id(mut self, id: CausationId) -> Self {
        self.causation_id = Some(id);
        self
    }

    /// Set the destination module.
    pub fn destination(mut self, dest: ModuleId) -> Self {
        self.destination = Some(dest);
        self
    }

    /// Set the timestamp explicitly (defaults to `Utc::now()`).
    ///
    /// Useful in tests for deterministic time or replay scenarios.
    pub fn timestamp(mut self, ts: DateTime<Utc>) -> Self {
        self.timestamp = Some(ts);
        self
    }

    /// Set the delivery priority.
    pub fn priority(mut self, p: Priority) -> Self {
        self.priority = p;
        self
    }

    /// Set the time-to-live duration.
    pub fn ttl(mut self, ttl: chrono::Duration) -> Self {
        self.ttl = Some(ttl);
        self
    }

    /// Set the trace context.
    pub fn trace_context(mut self, ctx: TraceContext) -> Self {
        self.trace_context = Some(ctx);
        self
    }

    /// Build the `MessageEnvelope`, consuming the builder.
    ///
    /// # Errors
    /// Returns `BuilderError` if `source`, `content_type`, or `payload` were not set.
    pub fn build(self) -> Result<MessageEnvelope, BuilderError> {
        let source = self.source.ok_or(BuilderError::MissingSource)?;
        let payload = self.payload.ok_or(BuilderError::MissingPayload)?;
        let content_type = self.content_type.ok_or(BuilderError::MissingContentType)?;

        Ok(MessageEnvelope {
            id: MessageId::new(),
            correlation_id: self.correlation_id,
            causation_id: self.causation_id,
            source,
            destination: self.destination,
            timestamp: self.timestamp.unwrap_or_else(Utc::now),
            payload,
            content_type,
            priority: self.priority,
            ttl: self.ttl,
            sequence: 0,
            retry_count: 0,
            trace_context: self.trace_context,
        })
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;
    use crate::value::SemVer;

    fn test_module_id(name: &str, major: u32, minor: u32, patch: u32) -> ModuleId {
        ModuleId::new(name, SemVer::new(major, minor, patch))
    }

    fn test_content_type(s: &str) -> ContentType {
        ContentType::new(s)
    }

    // ─── TraceContext ─────────────────────────────────────────────────────

    #[test]
    fn trace_context_new() {
        let ctx = TraceContext {
            trace_id: "trace-1".into(),
            span_id: "span-1".into(),
            parent_span_id: None,
        };
        assert_eq!(ctx.trace_id, "trace-1");
        assert_eq!(ctx.span_id, "span-1");
        assert!(ctx.parent_span_id.is_none());
    }

    #[test]
    fn trace_context_with_parent() {
        let ctx = TraceContext {
            trace_id: "trace-1".into(),
            span_id: "span-2".into(),
            parent_span_id: Some("span-1".into()),
        };
        assert_eq!(ctx.parent_span_id, Some("span-1".into()));
    }

    #[test]
    fn trace_context_clone() {
        let ctx = TraceContext {
            trace_id: "t".into(),
            span_id: "s".into(),
            parent_span_id: None,
        };
        let cloned = ctx.clone();
        assert_eq!(ctx.trace_id, cloned.trace_id);
    }

    // ─── MessageEnvelopeBuilder ───────────────────────────────────────────

    #[test]
    fn builder_via_new_sets_required_fields() {
        let src = test_module_id("src", 1, 0, 0);
        let ct = test_content_type("app/octet-stream");
        let payload = vec![1, 2, 3];

        let env = MessageEnvelopeBuilder::new(src.clone(), ct.clone(), payload.clone())
            .build()
            .expect("builder with all required fields should succeed");

        assert_eq!(env.source, src);
        assert_eq!(env.content_type, ct);
        assert_eq!(env.payload, payload);
        assert!(!env.id.as_uuid().is_nil());
        assert_eq!(env.priority, Priority::Normal);
        assert_eq!(env.sequence, 0);
        assert_eq!(env.retry_count, 0);
        assert!(env.destination.is_none());
        assert!(env.causation_id.is_none());
        assert!(env.ttl.is_none());
        assert!(env.trace_context.is_none());
    }

    #[test]
    fn builder_sets_all_fields() {
        let src = test_module_id("src", 1, 0, 0);
        let dst = test_module_id("dst", 2, 0, 0);
        let ct = test_content_type("app/json");
        let payload = b"hello".to_vec();
        let corr = CorrelationId::new();
        let cause = CausationId::new();
        let ctx = TraceContext {
            trace_id: "trace-1".into(),
            span_id: "span-1".into(),
            parent_span_id: None,
        };

        let env = MessageEnvelopeBuilder::default()
            .source(src.clone())
            .content_type(ct.clone())
            .payload(payload.clone())
            .correlation_id(corr)
            .causation_id(cause)
            .destination(dst.clone())
            .priority(Priority::High)
            .ttl(chrono::Duration::seconds(30))
            .trace_context(ctx.clone())
            .build()
            .expect("builder with all fields should succeed");

        assert_eq!(env.source, src);
        assert_eq!(env.content_type, ct);
        assert_eq!(env.payload, payload);
        assert_eq!(env.correlation_id, corr);
        assert_eq!(env.causation_id, Some(cause));
        assert_eq!(env.destination, Some(dst));
        assert_eq!(env.priority, Priority::High);
        assert_eq!(env.ttl, Some(chrono::Duration::seconds(30)));
        assert!(env.trace_context.is_some());
        let env_ctx = env.trace_context.as_ref().unwrap();
        assert_eq!(env_ctx.trace_id, ctx.trace_id);
        assert_eq!(env_ctx.span_id, ctx.span_id);
        assert_eq!(env_ctx.parent_span_id, ctx.parent_span_id);
    }

    #[test]
    fn builder_errors_without_source() {
        let ct = test_content_type("app/json");
        let payload = vec![];
        let result = MessageEnvelopeBuilder::default()
            .content_type(ct)
            .payload(payload)
            .build();
        assert!(matches!(result, Err(BuilderError::MissingSource)));
    }

    #[test]
    fn builder_errors_without_content_type() {
        let src = test_module_id("src", 1, 0, 0);
        let payload = vec![];
        let result = MessageEnvelopeBuilder::default()
            .source(src)
            .payload(payload)
            .build();
        assert!(matches!(result, Err(BuilderError::MissingContentType)));
    }

    #[test]
    fn builder_errors_without_payload() {
        let src = test_module_id("src", 1, 0, 0);
        let ct = test_content_type("app/json");
        let result = MessageEnvelopeBuilder::default()
            .source(src)
            .content_type(ct)
            .build();
        assert!(matches!(result, Err(BuilderError::MissingPayload)));
    }

    #[test]
    fn builder_default_correlation_id_is_random() {
        let src = test_module_id("src", 1, 0, 0);
        let ct = test_content_type("app/json");
        let payload = vec![];

        let e1 = MessageEnvelopeBuilder::new(src.clone(), ct.clone(), payload.clone())
            .build()
            .unwrap();
        let e2 = MessageEnvelopeBuilder::new(src, ct, payload)
            .build()
            .unwrap();
        assert_ne!(e1.correlation_id, e2.correlation_id);
    }

    // ─── MessageEnvelope ──────────────────────────────────────────────────

    #[test]
    fn envelope_is_expired_no_ttl() {
        let src = test_module_id("src", 1, 0, 0);
        let ct = test_content_type("app/json");
        let env = MessageEnvelopeBuilder::new(src, ct, vec![])
            .build()
            .unwrap();
        assert!(
            !env.is_expired(),
            "envelope without TTL should never expire"
        );
    }

    #[test]
    fn envelope_is_expired_with_ttl_future() {
        let src = test_module_id("src", 1, 0, 0);
        let ct = test_content_type("app/json");
        let env = MessageEnvelopeBuilder::new(src, ct, vec![])
            .ttl(chrono::Duration::hours(1))
            .build()
            .unwrap();
        assert!(
            !env.is_expired(),
            "envelope with 1h TTL should not be expired yet"
        );
    }

    #[test]
    fn envelope_builder_convenience() {
        let env = MessageEnvelope::builder();
        let built = env
            .source(test_module_id("s", 1, 0, 0))
            .content_type(test_content_type("ct"))
            .payload(vec![0u8])
            .build()
            .unwrap();
        assert_eq!(built.sequence, 0);
    }

    #[test]
    fn envelope_serde_roundtrip() {
        let src = test_module_id("src", 1, 0, 0);
        let ct = test_content_type("app/json");
        let payload = vec![10, 20, 30];

        let env = MessageEnvelopeBuilder::new(src, ct, payload)
            .priority(Priority::Critical)
            .build()
            .unwrap();

        let json = serde_json::to_string(&env).unwrap();
        let deserialized: MessageEnvelope = serde_json::from_str(&json).unwrap();

        assert_eq!(env.id, deserialized.id);
        assert_eq!(env.source, deserialized.source);
        assert_eq!(env.content_type, deserialized.content_type);
        assert_eq!(env.payload, deserialized.payload);
        assert_eq!(env.priority, deserialized.priority);
        assert_eq!(env.sequence, deserialized.sequence);
    }
}
